#:schema node_modules/wrangler/config-schema.json
name = "cloudflare-worker-gemini-starter-kit"
main = "src/index.ts"
compatibility_date = "2024-09-03"
compatibility_flags = ["nodejs_compat"]

# Variable bindings. These are arbitrary, plaintext strings (similar to environment variables)
# Docs:
# - https://developers.cloudflare.com/workers/wrangler/configuration/#environment-variables
# Note: Use secrets to store sensitive data.
# - https://developers.cloudflare.com/workers/configuration/secrets/
[vars]
GOOGLE_GEMINI_API_KEY = "AIzaSyDxD7WiixJUVw6h0HWqW6lS8pHpVihnNTM"
CLOUDFLARE_ACCOUNT_ID = "4b4ec8bb6f23f3dcf72d173347ada9e2"
CLOUDFLARE_AI_GATEWAY_NAME = "xgateway"